name: uzslr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - ipykernel
  - pytorch
  - torchvision
  - numpy=1.26.4
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - opencv
  - pip:
      - -r requirements.txt
